version: "3.7"
services:
  owt-server:
    build:
      context: ./owt-server
      args:
        - http_proxy
        - https_proxy
    environment:
      WAIT_HOSTS: "mongo:27017"
    ports:
      - "3000:3000"
      - "3300:3300"
      - "8080:8080"
    volumes:
      - "${DATA_DIR}/owt-server/logs:/owt-server/dist/logs"
    command: sh -c "/wait && /start.sh"
    depends_on:
      - mongo
  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
    volumes:
      - "${DATA_DIR}/mongo/db:/data/db"
      - "${DATA_DIR}/mongo/configdb:/data/configdb"
